---
- name: install and configure the witzbot app
  hosts: 'shoppingBot'

  tasks:
    - name: "include vault variables"
      include_vars: "vault.yml"

    - name: "Zip up the application directory"
      archive:
        path: "../src"
        dest: "witzbot.tgz"
      delegate_to: localhost

    - name: "Create /apps directory"
      file:
        path: "/apps/witzbot"
        state: directory
        owner: heidi
        group: heidi
      become: yes

    - name: "Unarchive witzbot.tgz"
      unarchive:
        src: "witzbot.tgz"
        dest: "/apps/witzbot"
        owner: heidi
        group: heidi

    - name: Make sure pip is present
      apt:
        name: "python3-pip"
        state: latest
      become: yes

    - name: "Install required python modules from requirements.txt"
      pip:
        requirements: /apps/witzbot/src/requirements.txt
        executable: pip3.8

    - name: "Start bot"
      command: "python3.8 /apps/witzbot/src/index.py"
      async: 2592000               # 60*60*24*30 – 1 month
      poll: 0
      environment:
        WB_CLIENT_ID: "{{WB_CLIENT_ID}}"
        WB_CLIENT_SIGNING_SECRET: "{{WB_CLIENT_SIGNING_SECRET}}"
        WB_CLIENT_BOT_TOKEN: "{{WB_CLIENT_BOT_TOKEN}}"
        WB_DEFAULT_CHANNEL: "{{WB_DEFAULT_CHANNEL}}"
